version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: 'db-vendas-online'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 28017:27017