version: "3"

services:
  JDBC-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DB: "vendas_online"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "calto@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - JDBC-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
